///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PaymentChannel {
/*
{
  "name": "logo",
  "logo": "name"
} 
*/

  String? name;
  String? logo;

  PaymentChannel({
    this.name,
    this.logo,
  });
  PaymentChannel.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    logo = json['logo']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['logo'] = logo;
    return data;
  }
}
