///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Category {
/*
{
  "id": "",
  "type": 1,
  "categoryName": ""
} 
*/

  String? id;
  int? type;
  String? categoryName;

  Category({
    this.id,
    this.type,
    this.categoryName,
  });
  Category.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    type = int.tryParse(json['type']?.toString() ?? '');
    categoryName = json['categoryName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['type'] = type;
    data['categoryName'] = categoryName;
    return data;
  }
}
