///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AdditionOptional {
/*
{
  "name": "",
  "price": 123
} 
*/

  String? name;
  int? price;

  AdditionOptional({
    this.name,
    this.price,
  });
  AdditionOptional.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    price = int.tryParse(json['price']?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['price'] = price;
    return data;
  }
}

class Addition {
/*
{
  "id": "",
  "additionName": "",
  "optional": [
    {
      "name": "",
      "price": 123
    }
  ]
} 
*/

  String? id;
  String? additionName;
  List<AdditionOptional?>? optional;

  Addition({
    this.id,
    this.additionName,
    this.optional,
  });
  Addition.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    additionName = json['additionName']?.toString();
    if (json['optional'] != null && (json['optional'] is List)) {
      final v = json['optional'];
      final arr0 = <AdditionOptional>[];
      v.forEach((v) {
        arr0.add(AdditionOptional.fromJson(v));
      });
      optional = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['additionName'] = additionName;
    if (optional != null) {
      final v = optional;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['optional'] = arr0;
    }
    return data;
  }
}
