///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CategoryRadio {
/*
{
  "id": "",
  "type": 1,
  "categoryName": "",
  "isSelected": false
} 
*/

  String? id;
  int? type;
  String? categoryName;
  bool? isSelected;

  CategoryRadio({
    this.id,
    this.type,
    this.categoryName,
    this.isSelected,
  });
  CategoryRadio.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    type = int.tryParse(json['type']?.toString() ?? '');
    categoryName = json['categoryName']?.toString();
    isSelected = json['isSelected'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['type'] = type;
    data['categoryName'] = categoryName;
    data['isSelected'] = isSelected;
    return data;
  }
}
