///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Product {
/*
{
  "id": "",
  "productName": "",
  "description": "",
  "category": "",
  "image": "",
  "price": 12345,
  "isStock": false,
  "isReady": false
} 
*/

  String? id;
  String? productName;
  String? description;
  String? category;
  String? image;
  int? price;
  bool? isStock;
  bool? isReady;

  Product({
    this.id,
    this.productName,
    this.description,
    this.category,
    this.image,
    this.price,
    this.isStock,
    this.isReady,
  });
  Product.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    productName = json['productName']?.toString();
    description = json['description']?.toString();
    category = json['category']?.toString();
    image = json['image']?.toString();
    price = int.tryParse(json['price']?.toString() ?? '');
    isStock = json['isStock'];
    isReady = json['isReady'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['productName'] = productName;
    data['description'] = description;
    data['category'] = category;
    data['image'] = image;
    data['price'] = price;
    data['isStock'] = isStock;
    data['isReady'] = isReady;
    return data;
  }
}
